
# Set defaults
export FPM_MAX_CHILDREN=${FPM_MAX_CHILDREN:-5}
export FPM_START_SERVERS=${FPM_START_SERVERS:-2}
export FPM_MIN_SPARE_SERVERS=${FPM_MIN_SPARE_SERVERS:-1}
export FPM_MAX_SPARE_SERVERS=${FPM_MAX_SPARE_SERVERS:-3}
export FPM_PROCESS_IDLE_TIMEOUT=${FPM_PROCESS_IDLE_TIMEOUT:-"10s"}
export FPM_MAX_REQUESTS=${FPM_MAX_REQUESTS:-0}

envsubst '$FPM_MAX_CHILDREN $FPM_START_SERVERS $FPM_MIN_SPARE_SERVERS $FPM_MAX_SPARE_SERVERS $FPM_PROCESS_IDLE_TIMEOUT $FPM_MAX_REQUESTS' \
  < "/etc/php/php-fpm.d/www.conf.template" > "/etc/php/php-fpm.d/www.conf"
